services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dsa_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dsa_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    depends_on:
      - backend
